; VCardix - vCard, CSV and JSON Contact Manager Software
; VCardix - Polish Lang File.
; (C) Copyright 2025-2026, Eray Türkay.
; Publisher: Türkaysoft
; Project Type: Open Source
; License: MIT License
; Website: https://turkaysoft.com
; GitHub: https://github.com/turkaysoft/vcardix

[Main]
lang_name = Polish / Poland
lang_tag = pl
translator = TS Translator Team
vcardix_version = v26.7

[HeaderMenu]
header_menu_file = Plik
header_menu_sorting = Tryb sortowania
header_menu_vcard_version = Wersja VCard
header_menu_settings = Ustawienia
header_menu_theme = Motyw
header_menu_language = Język (Language)
header_menu_start = Start
header_menu_update = Sprawdź aktualizację
header_menu_donate = Darowizna
header_menu_about = O programie

[HeaderFileContent]
header_fc_import = Importuj plik
header_fc_export = Eksportuj plik

[HeaderVCardVersion]
header_vcard_21 = vCard 2.1
header_vcard_30 = vCard 3.0
header_vcard_40 = vCard 4.0

[HeaderSortingMode]
header_sm_full = Pełne imię i nazwisko
header_sm_firstname = Imię
header_sm_lastname = Nazwisko
header_sm_phonemobile = Telefon komórkowy

[HeaderThemes]
theme_light = Motyw jasny
theme_dark = Motyw ciemny
theme_system = Motyw systemowy

[HeaderLangs]
lang_ar = Arabski (Arabic)
lang_zh = Chiński (Chinese)
lang_en = Angielski (English)
lang_nl = Holenderski (Dutch)
lang_fr = Francuski (French)
lang_de = Niemiecki (German)
lang_hi = Hindi (Hindi)
lang_it = Włoski (Italian)
lang_ja = Japoński (Japanese)
lang_ko = Koreański (Korean)
lang_pl = Polski (Polish)
lang_pt = Portugalski (Portuguese)
lang_ru = Rosyjski (Russian)
lang_es = Hiszpański (Spanish)
lang_tr = Turecki (Turkish)

[LangChange]
lang_change_notification = Język został zmieniony.{0}Niektóre pola wymagają ponownego uruchomienia programu, aby zastosować zmiany.{1}Czy chcesz teraz ponownie uruchomić program?

[HeaderViewMode]
header_view_mode_windowed = Tryb okienkowy
header_view_mode_full_screen = Pełny ekran

[CxImageMenu]
cxim_select = Wybierz / Zmień obraz
cxim_view = Wyświetl obraz
cxim_save = Zapisz obraz jako
cxim_remove = Usuń obraz

[HeaderHelp]
header_help_info_notification = {0} jest już otwarty.

; UI
; ====================================================================

[VCardixUI]
vcui_search = Szukaj:
vcui_add = DODAJ
vcui_update = AKTUALIZUJ
vcui_delete = USUŃ
vcui_f_name = Imię:
vcui_f_sec_name = Drugie imię:
vcui_f_surname = Nazwisko:
vcui_f_birthday = Data urodzenia:
vcui_f_phone_cell = Telefon komórkowy:
vcui_f_phone_home = Telefon domowy:
vcui_f_phone_work = Telefon służbowy:
vcui_f_email_1 = Adres e-mail 1:
vcui_f_email_2 = Adres e-mail 2:
vcui_f_email_3 = Adres e-mail 3:
vcui_f_address = Adres:
vcui_f_organization = Organizacja:
vcui_f_website = Strona internetowa:
vcui_f_note = Notatka:
vcui_f_profile_image = Zdjęcie profilowe:
vcui_bottom_ready = {0} osoba gotowa
vcui_bottom_ready_empty = Oczekiwanie na dodanie...
vcui_new_person_add_success = Nowa osoba została pomyślnie dodana.
vcui_new_person_add_warning = Pole imienia nie może być puste. Wypełnij je i spróbuj ponownie.
vcui_update_person_query = Czy na pewno chcesz zaktualizować wybraną osobę o nazwie '{0}'?
vcui_update_person_success = Osoba została pomyślnie zaktualizowana.
vcui_person_not_found = Nie znaleziono osoby. Spróbuj ponownie.
vcui_update_person_process_warning = Wybierz osobę do aktualizacji.
vcui_delete_person_query = Czy na pewno chcesz usunąć wybraną osobę o nazwie '{0}'?
vcui_delete_person_success = Osoba została pomyślnie usunięta.
vcui_delete_failed = Wystąpił błąd podczas usuwania osoby. Spróbuj ponownie.{0}Błąd: {1}
vcui_delete_person_process_warning = Wybierz osobę do usunięcia.
vcui_select_image = {0} - Wybierz obraz
vcui_image_filter = Pliki graficzne {0}
vcui_image_person_not_added_warning = Nie dodano jeszcze żadnych osób. Najpierw dodaj osobę.
vcui_image_person_not_select_warning = Nie wybrano osoby. Wybierz osobę, aby dodać obraz.
vcui_image_size_limit_warning = Rozmiar pliku musi być równy lub mniejszy niż {0} MB. Wybierz mniejszy obraz.
vcui_image_save_title = {0} - Zapisz obraz jako
vcui_image_save_success = Obraz został pomyślnie zapisany jako '{0}'.{1}Czy chcesz otworzyć lokalizację pliku?
vcui_image_save_failed = Błąd zapisu obrazu. Spróbuj ponownie.{0}Błąd: {1}
vcui_image_change_info = Dla wybranej osoby istnieje już obraz. Czy chcesz go zmienić?
vcui_image_import_success = Obraz został pomyślnie dodany.
vcui_image_update_success = Obraz został pomyślnie zaktualizowany.
vcui_image_remove_success = Obraz został pomyślnie usunięty.
vcui_image_import_failed = Błąd przetwarzania obrazu. Spróbuj ponownie.{0}Błąd: {1}
vcui_import_warning = Masz niezapisane dane. Jeśli zaimportujesz, niezapisane dane zostaną usunięte.{0}Czy potwierdzasz?
vcui_import_warning_exit = Masz niezapisane dane. Czy chcesz je zapisać przed zamknięciem programu?{0}Program zamknie się automatycznie po zapisaniu.
vcui_import_warning_merge = Na liście znajdują się kontakty.{0}Wybierz Tak, aby zastąpić listę (bieżące dane zostaną utracone).{1}Wybierz Nie, aby scalić z bieżącymi danymi (duplikaty zostaną pominięte).{2}Wybierz Anuluj, aby anulować.
vcui_vcard_merge_success = Plik vCard został pomyślnie scalony. Zdublowane rekordy zostały pominięte.
vcui_csv_merge_success = Plik CSV został pomyślnie scalony. Zdublowane rekordy zostały pominięte.
vcui_json_merge_success = Plik JSON został pomyślnie scalony. Zdublowane rekordy zostały pominięte.
vcui_merge_skipped = {0} (pominięto {1} zdublowanych rekordów.)
vcui_load = {0} - Wczytywanie pliku...
vcui_save = {0} - Zapisywanie pliku...
vcui_vcard_import_success = Plik vCard został pomyślnie zaimportowany.
vcui_csv_import_success = Plik CSV został pomyślnie zaimportowany.
vcui_json_import_success = Plik JSON został pomyślnie zaimportowany.
vcui_single_file_warning = Przeciągnij tylko jeden plik naraz.
vcui_dad_filter = Dozwolone są tylko pliki *.vcf, *.csv, *.json lub obrazy (.jpg, .png itp.). Przeciągnij poprawny plik.
vcui_dad_failed = Błąd przetwarzania. Spróbuj ponownie.{0}Błąd: {1}
vcui_select_file = {0} - Wybierz plik
vcui_select_filter = Pliki vCard, CSV i JSON {0}
vcui_select_failed = Błąd odczytu. Spróbuj ponownie.{0}Błąd: {1}
vcui_export_file = {0} - Zapisz plik
vcui_export_warning = Brak danych do zapisania. Utwórz nowe dane i spróbuj ponownie.
vcui_export_name = {0}_{1}_{2}
vcui_export_filter = Plik vCard {0}Plik CSV {1}Plik JSON {2}
vcui_export_40_change_warning = vCard 4.0 można poprawnie wyświetlać tylko na nowszych urządzeniach. Na starszych może nie działać poprawnie.{0}Czy chcesz kontynuować?
vcui_export_40_warning = Plik zostanie zapisany w formacie vCard 4.0. Na starszych urządzeniach może być niepoprawnie wyświetlany.{0}Czy chcesz kontynuować?
vcui_vcard_export_success = Plik vCard został pomyślnie zapisany w katalogu '{0}'.{1}Czy chcesz go otworzyć?
vcui_csv_export_success = Plik CSV został pomyślnie zapisany w katalogu '{0}'.{1}Czy chcesz go otworzyć?
vcui_json_export_success = Plik JSON został pomyślnie zapisany w katalogu '{0}'.{1}Czy chcesz go otworzyć?
vcui_export_failed = Błąd zapisu. Spróbuj ponownie.{0}Błąd: {1}
vcui_search_hover = Szukaj
vcui_adress_window_hover = Edytor adresu
vcui_profile_image_hover = Menu obrazu

[VCardixOther]
vca_name = Edytor adresu
vca_title = {0} - Edytuj adres
vca_pobox = Skrytka pocztowa:
vca_apartment = Informacje o mieszkaniu / jednostce:
vca_street = Ulica / dzielnica:
vca_city = Miasto:
vca_region = Region / Stan / Prowincja:
vca_po_code = Kod pocztowy:
vca_country = Kraj:
vca_save = ZAPISZ
vca_cancel = ANULUJ
vci_title = {0} - Podgląd obrazu
vci_img_save = Zapisz obraz

; SOFTWARE UPDATE
; ====================================================================

[SoftwareUpdate]
su_title = {0} - Sprawdzanie aktualizacji
su_available = Dostępna jest nowa wersja dla {0}!{1}Twoja aktualna wersja: v{2}{3}Najnowsza wersja: v{4}{5}Naciśnij Tak, aby uruchomić kreatora aktualizacji TS i pobrać nową wersję.
su_not_available = {0} jest aktualny.{1}Wersja klienta: v{2}
su_newer = Gratulacje!{0}Jesteś wśród pierwszych osób, które mogą wypróbować wersję {1}, która nie została jeszcze udostępniona publicznie!
su_ts_updater_c_running = Kreator aktualizacji TS jest już uruchomiony. Aplikacja zostanie zamknięta...
su_ts_updater_not_available = Plik {0} nie został znaleziony. Nastąpi przekierowanie do strony pobierania na GitHubie...
su_not_connection = Nie można ukończyć sprawdzania aktualizacji z powodu braku połączenia z Internetem.{0}Sprawdź połączenie internetowe i spróbuj ponownie.
su_error = Wystąpił błąd podczas sprawdzania aktualizacji. Spróbuj ponownie później.{0}Błąd: {1}

; TS UPDATER
; ====================================================================

[TSUpdater]
tsu_title = {0} - Kreator aktualizacji {1} - {2}
tsu_subtitle = TS - Kreator aktualizacji
tsu_ui_loading = Ładowanie...
tsu_ui_release_notes = Informacje o wydaniu
tsu_version_not_installed = Obecnie: nie zainstalowano
tsu_app_default_name = Aplikacja
tsu_status_checking = Sprawdzanie...
tsu_status_ready_update = Gotowe do aktualizacji lub instalacji.
tsu_status_ready_launch = Gotowe do uruchomienia aplikacji.
tsu_status_downloading = Pobieranie...
tsu_status_extracting = Rozpakowywanie plików...
tsu_status_launching = Uruchamianie aplikacji...
tsu_status_error = Wystąpił błąd. Spróbuj ponownie.
tsu_status_preparing = Przygotowywanie...
tsu_button_preparing = Przygotowywanie...
tsu_button_launching = Uruchamianie...
tsu_button_retry = Ponów
tsu_button_start_update = Rozpocznij aktualizację
tsu_button_start_install = Rozpocznij instalację
tsu_button_start_app = Uruchom aplikację
tsu_button_start = Start
tsu_substatus_checking_versions = Sprawdzanie wersji aplikacji...
tsu_substatus_download_starting = Rozpoczynanie pobierania...
tsu_substatus_extracting_files = Rozpakowywanie plików...
tsu_substatus_preparing_app = Przygotowywanie do uruchomienia aplikacji...
tsu_substatus_please_wait = Proszę czekać...
tsu_status_new_version_available = Dostępna jest nowa wersja dla {0}!
tsu_status_ready_for_install = {0} jest gotowy do instalacji.
tsu_status_app_up_to_date = {0} jest aktualny.
tsu_status_connecting_to_server = Łączenie z serwerem...
tsu_error_url_message = Nie udało się wygenerować adresu URL aktualizacji. Sprawdź ustawienia.
tsu_error_timeout_message = Nie udało się połączyć z serwerem w wyznaczonym czasie. Sprawdź połączenie internetowe i spróbuj ponownie.
tsu_error_connection_message = Błąd połączenia z serwerem:
tsu_error_version_check_message = Błąd sprawdzania wersji:
tsu_error_download_url_message = Adres URL pobierania nie jest skonfigurowany lub nie można go wygenerować.
tsu_error_invalid_download_url = Adres URL pobierania jest pusty lub nieprawidłowy.
tsu_error_config_load = Nie udało się załadować konfiguracji aplikacji.
tsu_error_on_startup = Wystąpił błąd podczas uruchamiania aplikacji:
tsu_error_release_page_not_configured = Adres URL strony informacji o wydaniu nie jest skonfigurowany.
tsu_error_open_release_page = Nie udało się otworzyć strony informacji o wydaniu:
tsu_error_download_message = Wystąpił błąd podczas pobierania:
tsu_error_zip_not_found = Nie znaleziono pliku ZIP. Kliknij przycisk, aby spróbować ponownie.
tsu_error_extraction_failed = Nie udało się ukończyć instalacji. Kliknij przycisk, aby spróbować ponownie.
tsu_error_invalid_file_path = Wykryto nieprawidłową ścieżkę pliku (zapobieżono Zip Slip).
tsu_error_self_exe_update = Błąd aktualizacji pliku wykonywalnego:
tsu_error_extraction_files = Wystąpił błąd podczas rozpakowywania plików:
tsu_error_during_operation = Wystąpił błąd podczas operacji:
tsu_error_launch_app = Nie udało się uruchomić aplikacji:
tsu_error_launch_exception = Wystąpił błąd podczas uruchamiania aplikacji:
tsu_app_will_exit = Program zostanie zamknięty.
tsu_ask_view_release_notes = Czy chcesz wyświetlić opublikowane notatki do wersji dla {0}?{1}Notatki do wersji mogą zawierać ważne zmiany i informacje, o których należy wiedzieć.
tsu_confirm_new_version = Dostępna jest nowa wersja dla {0}.{1}Czy chcesz pobrać i zainstalować nową wersję?
tsu_confirm_install = {0} zostanie pobrany i zainstalowany.{1}Czy chcesz kontynuować?
tsu_success_update_completed = {0} został pomyślnie zaktualizowany.
tsu_success_install_completed = {0} został pomyślnie zainstalowany.
tsu_prompt_launch_after_update = Aktualizacja {0} została zakończona. Czy chcesz teraz uruchomić aplikację?
tsu_prompt_launch_app = Czy chcesz teraz uruchomić {0}?
tsu_prompt_launch_after_install = Instalacja {0} została zakończona. Czy chcesz teraz uruchomić aplikację?
tsu_current_version_label = Aktualna: {0}
tsu_exe_not_found = Nie znaleziono pliku wykonywalnego (.exe). Sprawdź lokalizację pliku.
tsu_error_file_in_use = {0} jest aktualnie uruchomiony. Zamknij uruchomiony program przed aktualizacją.
tsu_online_version_label = Najnowsza: {0}
tsu_zip_not_found_error = Nie znaleziono pliku ZIP.
tsu_download_completed_label = pobrano
tsu_file_label = Plik:

; ABOUT
; ====================================================================

[SoftwareAbout]
sa_title = {0} - Informacje
sa_website_link = Strona
sa_github_link = GitHub
sa_donate_link = Wsparcie
sa_lang_name = Język
sa_lang_translator = Tłumacz